# Generated by Django 4.0.3 on 2022-04-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse', models.IntegerField(default=0)),
                ('pressure', models.IntegerField(default=0)),
                ('altitude', models.IntegerField(default=0)),
                ('temp', models.IntegerField(default=0)),
            ],
        ),
    ]
