# Generated by Django 4.0.3 on 2022-04-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_data_options_data_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='altitude',
        ),
    ]
